modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mega_project"
version="1.5.1"
displayName="MEGA Project"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="dZ__, Kelso with MCreator"

[[dependencies.mega_project]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.mega_project]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"

