modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mega_project"
version="1.0.0"
displayName="MEGA Project"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="matus, MCreator"

[[dependencies.mega_project]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




